"""add app bundle

Revision ID: a4bfbcc9e6e2
Revises: c05ac2a95c5f
Create Date: 2025-03-22 01:42:16.389743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bfbcc9e6e2'
down_revision = 'c05ac2a95c5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_product_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('skin_type', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_product_items_id'), 'task_product_items', ['id'], unique=False)
    op.create_table('task_skin_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('skin_type', sa.String(), nullable=False),
    sa.Column('problems', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_skin_items_id'), 'task_skin_items', ['id'], unique=False)
    op.drop_index('ix_task_items_id', table_name='task_items')
    op.drop_table('task_items')
    op.add_column('tasks', sa.Column('app_bundle', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('user_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'user_id')
    op.drop_column('tasks', 'app_bundle')
    op.create_table('task_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_items_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='task_items_pkey')
    )
    op.create_index('ix_task_items_id', 'task_items', ['id'], unique=False)
    op.drop_index(op.f('ix_task_skin_items_id'), table_name='task_skin_items')
    op.drop_table('task_skin_items')
    op.drop_index(op.f('ix_task_product_items_id'), table_name='task_product_items')
    op.drop_table('task_product_items')
    # ### end Alembic commands ###
